//! Raw declarations for the subset of libclixon 7.8 (and libcligen's cbuf)
//! that backend plugins use.
//!
//! Written by hand from the installed headers instead of generated by
//! bindgen: the subset is small, and the Yocto build then needs no libclang.
//! When moving to another clixon version, compare against
//! `clixon/clixon_plugin.h` (struct clixon_plugin_api),
//! `clixon/clixon_backend_transaction.h`, `clixon/clixon_json.h`,
//! `clixon/clixon_xml_io.h`, `clixon/clixon_log.h`, `clixon/clixon_err.h` and
//! `cligen/cligen_buf.h`.

#![allow(non_camel_case_types)]

use std::ffi::{c_char, c_int, c_void};

/// Linux (glibc and musl) `<sys/param.h>`.
pub const MAXPATHLEN: usize = 4096;

pub type clixon_handle = *mut c_void;
pub type transaction_data = *mut c_void;

macro_rules! opaque {
    ($($name:ident),*) => {$(
        #[repr(C)]
        pub struct $name {
            _private: [u8; 0],
        }
    )*};
}
opaque!(cxobj, cbuf, cvec, yang_stmt);

/// `enum yang_bind` (clixon_xml.h).
pub type yang_bind = c_int;
pub const YB_NONE: yang_bind = 0;
pub const YB_MODULE: yang_bind = 1;

/// `enum clixon_err` categories (clixon_err.h).
pub const OE_PLUGIN: c_int = 14;
pub const OE_FATAL: c_int = 16;

/// syslog(3) levels, as taken by `clixon_log_fn`.
pub const LOG_ERR: c_int = 3;
pub const LOG_WARNING: c_int = 4;
pub const LOG_NOTICE: c_int = 5;
pub const LOG_INFO: c_int = 6;
pub const LOG_DEBUG: c_int = 7;

pub type plginit_t = unsafe extern "C" fn(h: clixon_handle) -> *mut clixon_plugin_api;
pub type plgstart_t = unsafe extern "C" fn(h: clixon_handle) -> c_int;
pub type plgexit_t = unsafe extern "C" fn(h: clixon_handle) -> c_int;
pub type plgdaemon_t = unsafe extern "C" fn(h: clixon_handle) -> c_int;
pub type plgreset_t = unsafe extern "C" fn(h: clixon_handle, db: *const c_char) -> c_int;
pub type plgstatedata_t = unsafe extern "C" fn(
    h: clixon_handle,
    nsc: *mut cvec,
    xpath: *mut c_char,
    xconfig: *mut cxobj,
) -> c_int;
pub type trans_cb_t = unsafe extern "C" fn(h: clixon_handle, td: transaction_data) -> c_int;

/// A callback slot this crate never fills. Only its size matters: it is a
/// function pointer, and it stays NULL.
pub type unused_cb_t = unsafe extern "C" fn();

/// `struct clixon_plugin_api` (clixon_plugin.h).
///
/// In C the fields after `ca_userdef` are a union of the cli, restconf,
/// netconf and backend callback sets. The backend set is the largest member,
/// so the union has exactly its layout, and a backend plugin only ever uses
/// that member.
#[repr(C)]
pub struct clixon_plugin_api {
    pub ca_name: [c_char; MAXPATHLEN],
    pub ca_init: Option<plginit_t>,
    pub ca_start: Option<plgstart_t>,
    pub ca_exit: Option<plgexit_t>,
    pub ca_extension: Option<unused_cb_t>,
    pub ca_yang_mount: Option<unused_cb_t>,
    pub ca_yang_patch: Option<unused_cb_t>,
    pub ca_errmsg: Option<unused_cb_t>,
    pub ca_version: Option<unused_cb_t>,
    pub ca_userdef: Option<unused_cb_t>,
    pub u: backend_api,
}

/// `u.cau_backend` of `struct clixon_plugin_api`.
#[repr(C)]
pub struct backend_api {
    pub cb_pre_daemon: Option<plgdaemon_t>,
    pub cb_daemon: Option<plgdaemon_t>,
    pub cb_reset: Option<plgreset_t>,
    pub cb_statedata: Option<plgstatedata_t>,
    pub cb_system_only: Option<plgstatedata_t>,
    pub cb_lockdb: Option<unused_cb_t>,
    pub cb_trans_begin: Option<trans_cb_t>,
    pub cb_trans_validate: Option<trans_cb_t>,
    pub cb_trans_complete: Option<trans_cb_t>,
    pub cb_trans_commit: Option<trans_cb_t>,
    pub cb_trans_commit_done: Option<trans_cb_t>,
    pub cb_trans_commit_failed: Option<trans_cb_t>,
    pub cb_trans_revert: Option<trans_cb_t>,
    pub cb_trans_end: Option<trans_cb_t>,
    pub cb_trans_abort: Option<trans_cb_t>,
    pub cb_datastore_upgrade: Option<unused_cb_t>,
}

extern "C" {
    // cligen_buf.h
    pub fn cbuf_new() -> *mut cbuf;
    pub fn cbuf_free(cb: *mut cbuf);
    pub fn cbuf_get(cb: *mut cbuf) -> *mut c_char;
    pub fn cbuf_len(cb: *mut cbuf) -> usize;

    // clixon_backend_transaction.h
    pub fn transaction_src(td: transaction_data) -> *mut cxobj;
    pub fn transaction_target(td: transaction_data) -> *mut cxobj;

    // clixon_json.h
    pub fn clixon_json2cbuf(
        cb: *mut cbuf,
        x: *mut cxobj,
        pretty: c_int,
        skiptop: c_int,
        autocliext: c_int,
        system_only: c_int,
    ) -> c_int;
    pub fn xml2json_cbuf_vec(
        cb: *mut cbuf,
        vec: *mut *mut cxobj,
        veclen: usize,
        pretty: c_int,
        skiptop: c_int,
    ) -> c_int;

    // clixon_xml_io.h. clixon_xml_parse_string() is a static inline wrapper
    // around this with h = NULL.
    pub fn clixon_xml_parse_string1(
        h: clixon_handle,
        str_: *const c_char,
        yb: yang_bind,
        yspec: *mut yang_stmt,
        xt: *mut *mut cxobj,
        xerr: *mut *mut cxobj,
    ) -> c_int;

    // clixon_log.h
    pub fn clixon_log_fn(
        h: clixon_handle,
        user: c_int,
        level: c_int,
        x: *mut cxobj,
        format: *const c_char,
        ...
    ) -> c_int;

    // clixon_err.h
    pub fn clixon_err_fn(
        h: clixon_handle,
        fn_: *const c_char,
        line: c_int,
        category: c_int,
        suberr: c_int,
        xerr: *mut cxobj,
        format: *const c_char,
        ...
    ) -> c_int;
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::mem::size_of;

    #[test]
    fn plugin_api_layout() {
        // ca_name + 9 common callbacks + 16 backend callbacks.
        assert_eq!(
            size_of::<clixon_plugin_api>(),
            MAXPATHLEN + (9 + 16) * size_of::<usize>()
        );
    }
}
