#!/bin/sh
# Translates the MIBs that clixon_snmp serves into YANG (RFC 6643) with
# libsmi's smidump, into yang/mib: the MIBs in MIBS and the import closure
# of their translations. Modules named ietf-* come from scripts/vendor-yang.sh.
#
#   scripts/mib-to-yang.sh <libsmi-0.5.0 mibs directory>
#
# Run it in the dev container: dev/container.sh scripts/mib-to-yang.sh
# /usr/local/share/libsmi-mibs (the directory is optional there).
#
# RFC 6643 translates every object to config false, so these modules only
# describe state: SNMP cannot change the configuration.

set -eu

# The MANIFEST is sorted the same everywhere: sort and the shell's globs
# follow the locale, which puts "ietf-snmp@..." before or after
# "ietf-snmp-common@..." depending on how it treats punctuation.
export LC_ALL=C

MIBS="BRIDGE-MIB Q-BRIDGE-MIB RSTP-MIB"
LIBSMI_VERSION=0.5.0

src=${1:-/usr/local/share/libsmi-mibs}
top=$(cd "$(dirname "$0")/.." && pwd)
dst=$top/yang/mib

version=$(smidump -V 2>&1 | sed -n 's/^smidump \([0-9.]*\).*/\1/p')
if [ "$version" != "$LIBSMI_VERSION" ]; then
    echo "error: smidump is version ${version:-unknown}, expected $LIBSMI_VERSION" >&2
    exit 1
fi

SMIPATH=$src/ietf:$src/iana:$src/irtf:$src/tubs
export SMIPATH

imports() {
    sed -n 's/^[[:space:]]*import[[:space:]]\{1,\}\([A-Za-z0-9_.-]\{1,\}\).*/\1/p' "$1" | sort -u
}

rm -rf "$dst"
mkdir -p "$dst"

seen=""
todo=$MIBS
while [ -n "$todo" ]; do
    next=""
    for m in $todo; do
        case " $seen " in *" $m "*) continue ;; esac
        seen="$seen $m"
        case $m in ietf-*) continue ;; esac
        smidump -f yang "$m" > "$dst/$m.yang"
        # Q-BRIDGE-MIB imports RMON2-MIB for a single type, TimeFilter (the
        # index of dot1qVlanCurrentTable), which is timeticks. RMON2-MIB
        # would bring RMON-MIB, TOKEN-RING-RMON-MIB, RFC1213-MIB, ...: some
        # 16000 lines of YANG that clixon parses at every start.
        if [ "$m" = Q-BRIDGE-MIB ]; then
            sed -i \
                -e '/^  import RMON2-MIB {$/,/^  }$/d' \
                -e 's/rmon2-mib:TimeFilter/yang:timeticks/' \
                "$dst/$m.yang"
            if grep -q 'rmon2-mib:' "$dst/$m.yang"; then
                echo "error: Q-BRIDGE-MIB still refers to RMON2-MIB" >&2
                exit 1
            fi
        fi
        # RSTP-MIB adds dot1dStpVersion and dot1dStpTxHoldCount to
        # BRIDGE-MIB's dot1dStp group. smidump puts them in a dot1dStp
        # container of its own, together with copies of all of BRIDGE-MIB's
        # dot1dStp scalars: keep only the new ones, or clixon_snmp would
        # register the same OIDs twice.
        if [ "$m" = RSTP-MIB ]; then
            bridge_leaves=$(sed -n 's/^      leaf \([A-Za-z0-9]*\) {$/\1/p' "$dst/BRIDGE-MIB.yang")
            awk -v names=" $(echo $bridge_leaves) " '
                /^      leaf [A-Za-z0-9]+ \{$/ && index(names, " " $2 " ") { skip = 1 }
                !skip { print }
                skip && /^      }$/ { skip = 0; getline; if ($0 != "") print }
            ' "$dst/$m.yang" > "$dst/$m.yang.tmp"
            mv "$dst/$m.yang.tmp" "$dst/$m.yang"
        fi
        # smidump does not always import the modules of the types it uses
        # (RSTP-MIB uses yang:timeticks).
        if grep -q '^ *type yang:' "$dst/$m.yang" &&
            ! grep -q '^  import ietf-yang-types {$' "$dst/$m.yang"; then
            sed -i '0,/^  import /s//  import ietf-yang-types {\n    prefix "yang";\n  }\n\n  import /' "$dst/$m.yang"
        fi
        for prefix in $(sed -n 's/^ *\(type\|base\) \([A-Za-z0-9-]*\):.*/\2/p' "$dst/$m.yang" | sort -u); do
            if ! grep -q "^ *prefix \"$prefix\";$" "$dst/$m.yang"; then
                echo "error: $m uses prefix $prefix without importing its module" >&2
                exit 1
            fi
        done
        next="$next $(imports "$dst/$m.yang")"
    done
    todo=$next
done

{
    echo "# smidump $LIBSMI_VERSION -f yang, generated by scripts/mib-to-yang.sh"
    echo "# Q-BRIDGE-MIB: rmon2-mib:TimeFilter replaced by yang:timeticks"
    echo "# RSTP-MIB: copies of BRIDGE-MIB's dot1dStp scalars removed"
    (cd "$dst" && ls -1 ./*.yang | sed 's|^\./||')
} > "$dst/MANIFEST"
cat "$dst/MANIFEST"
