#!/bin/sh
# Copies the YANG modules the switch needs from an openconfig/public
# checkout and a YangModels/yang checkout into yang/vendor: the import
# closure of the modules in yang/ and of the MIB translations in yang/mib
# (scripts/mib-to-yang.sh, run that first), nothing else. openconfig/public
# is searched first.
#
#   scripts/vendor-yang.sh <openconfig/public checkout at OPENCONFIG_TAG> \
#       <YangModels/yang checkout at YANGMODELS_COMMIT>
#
# YangModels/yang provides the IETF modules openconfig/public does not
# have: ietf-snmp (RFC 7407) and ietf-yang-smiv2 (RFC 6643). They are
# copied to yang/vendor/yangmodels.
#
# OPENCONFIG_TAG: openconfig-if-ip must stay at 3.7.0 or older. From 3.8.0
# (openconfig/public v5.4.0) it imports openconfig-network-instance for uRPF,
# which drags BGP, IS-IS, OSPF, MPLS, AFT, ... into clixon's YANG parser, on a
# switch with 128 MiB of RAM. FORBIDDEN makes a bump that does this fail.

set -eu

# The MANIFEST is sorted the same everywhere: sort and the shell's globs
# follow the locale, which puts "ietf-snmp@..." before or after
# "ietf-snmp-common@..." depending on how it treats punctuation.
export LC_ALL=C

OPENCONFIG_TAG=v5.3.0
YANGMODELS_COMMIT=a4ea86b06aa63512e280f1665db6eaf8116bf059
# Installed by clixon itself in /usr/share/clixon.
CLIXON_PROVIDED="ietf-yang-types ietf-inet-types ietf-netconf-acm"
FORBIDDEN="openconfig-network-instance"

usage="usage: $0 <openconfig/public checkout> <YangModels/yang checkout>"
src=${1:?$usage}
yangmodels=${2:?$usage}
top=$(cd "$(dirname "$0")/.." && pwd)
dst=$top/yang/vendor

tag=$(git -C "$src" describe --tags --exact-match 2>/dev/null || echo "an untagged commit")
if [ "$tag" != "$OPENCONFIG_TAG" ]; then
    echo "error: $src is at $tag, expected $OPENCONFIG_TAG" >&2
    exit 1
fi
commit=$(git -C "$yangmodels" rev-parse HEAD 2>/dev/null || echo "not a git checkout")
if [ "$commit" != "$YANGMODELS_COMMIT" ]; then
    echo "error: $yangmodels is at $commit, expected $YANGMODELS_COMMIT" >&2
    exit 1
fi

# The statement, not description text like "include the": the name is
# followed by "{" or ";".
imports() {
    sed -n 's/^[[:space:]]*\(import\|include\)[[:space:]]\{1,\}\([A-Za-z0-9_.-]\{1,\}\)[[:space:]]*[{;].*/\2/p' "$@" | sort -u
}

# Prints "<source dir> <file>". YangModels/yang has name@revision.yang
# files and name.yang links to them: take the file.
find_module() {
    f=$(find "$src/release/models" "$src/third_party/ietf" \
        \( -name "$1.yang" -o -name "$1@*.yang" \) | head -n 1)
    if [ -n "$f" ]; then
        echo "$src $f"
        return
    fi
    f=$(find "$yangmodels/standard/ietf/RFC" -type f -name "$1@*.yang" | head -n 1)
    [ -z "$f" ] || echo "$yangmodels $f"
}

# Our own modules and the MIB translations are not vendored.
seen=""
for f in "$top"/yang/*.yang "$top"/yang/mib/*.yang; do
    m=$(basename "$f" .yang)
    seen="$seen ${m%%@*}"
done

rm -rf "$dst"
mkdir -p "$dst"

todo=$(imports "$top"/yang/*.yang "$top"/yang/mib/*.yang)
while [ -n "$todo" ]; do
    next=""
    for m in $todo; do
        case " $seen " in *" $m "*) continue ;; esac
        seen="$seen $m"
        case " $CLIXON_PROVIDED " in *" $m "*) continue ;; esac
        case " $FORBIDDEN " in
            *" $m "*)
                echo "error: $m is in the import closure" >&2
                exit 1
                ;;
        esac
        found=$(find_module "$m")
        if [ -z "$found" ]; then
            echo "error: module $m not found in $src or $yangmodels" >&2
            exit 1
        fi
        root=${found%% *}
        f=${found#* }
        rel=${f#"$root"/}
        [ "$root" = "$src" ] || rel=yangmodels/$rel
        install -D -m 0644 "$f" "$dst/$rel"
        echo "$rel"
        next="$next $(imports "$f")"
    done
    todo=$next
done | sort > "$dst/MANIFEST.tmp"

{
    echo "# openconfig/public $OPENCONFIG_TAG, generated by scripts/vendor-yang.sh"
    echo "# yangmodels/: YangModels/yang $YANGMODELS_COMMIT"
    cat "$dst/MANIFEST.tmp"
} > "$dst/MANIFEST"
rm "$dst/MANIFEST.tmp"
cat "$dst/MANIFEST"
