#!/bin/sh
# Copies the YANG modules the switch needs from an openconfig/public
# checkout into yang/vendor: the import closure of the modules in yang/,
# nothing else.
#
#   scripts/vendor-yang.sh <openconfig/public checkout at OPENCONFIG_TAG>
#
# OPENCONFIG_TAG: openconfig-if-ip must stay at 3.7.0 or older. From 3.8.0
# (openconfig/public v5.4.0) it imports openconfig-network-instance for uRPF,
# which drags BGP, IS-IS, OSPF, MPLS, AFT, ... into clixon's YANG parser, on a
# switch with 128 MiB of RAM. FORBIDDEN makes a bump that does this fail.

set -eu

OPENCONFIG_TAG=v5.3.0
# Installed by clixon itself in /usr/share/clixon.
CLIXON_PROVIDED="ietf-yang-types ietf-inet-types"
FORBIDDEN="openconfig-network-instance"

src=${1:?usage: $0 <openconfig/public checkout>}
top=$(cd "$(dirname "$0")/.." && pwd)
dst=$top/yang/vendor

tag=$(git -C "$src" describe --tags --exact-match 2>/dev/null || echo "an untagged commit")
if [ "$tag" != "$OPENCONFIG_TAG" ]; then
    echo "error: $src is at $tag, expected $OPENCONFIG_TAG" >&2
    exit 1
fi

imports() {
    sed -n 's/^[[:space:]]*\(import\|include\)[[:space:]]\{1,\}\([A-Za-z0-9_.-]\{1,\}\).*/\2/p' "$@" | sort -u
}

find_module() {
    find "$src/release/models" "$src/third_party/ietf" \
        \( -name "$1.yang" -o -name "$1@*.yang" \) | head -n 1
}

# Our own modules are not vendored.
seen=""
for f in "$top"/yang/*.yang; do
    m=$(basename "$f" .yang)
    seen="$seen ${m%%@*}"
done

rm -rf "$dst"
mkdir -p "$dst"

todo=$(imports "$top"/yang/*.yang)
while [ -n "$todo" ]; do
    next=""
    for m in $todo; do
        case " $seen " in *" $m "*) continue ;; esac
        seen="$seen $m"
        case " $CLIXON_PROVIDED " in *" $m "*) continue ;; esac
        case " $FORBIDDEN " in
            *" $m "*)
                echo "error: $m is in the import closure" >&2
                exit 1
                ;;
        esac
        f=$(find_module "$m")
        if [ -z "$f" ]; then
            echo "error: module $m not found in $src" >&2
            exit 1
        fi
        rel=${f#"$src"/}
        install -D -m 0644 "$f" "$dst/$rel"
        echo "$rel"
        next="$next $(imports "$f")"
    done
    todo=$next
done | sort > "$dst/MANIFEST.tmp"

{
    echo "# openconfig/public $OPENCONFIG_TAG, generated by scripts/vendor-yang.sh"
    cat "$dst/MANIFEST.tmp"
} > "$dst/MANIFEST"
rm "$dst/MANIFEST.tmp"
cat "$dst/MANIFEST"
