#!/usr/bin/env python3
"""Writes the compose file of a lab topology to stdout.

    gen-compose.py ring [N]          N switches sw1..swN in a ring (default 5),
                                     sw1 the root: compose.yaml
    gen-compose.py chain [N]         r1 - s1 - ... - sN - r2 (default 36), r1
                                     priority 0, r2 4096: chain.yaml

Options for both: --protocol (RSTP; none: spanning tree off, only safe
without loops), --max-age, --forwarding-delay.

    lab/gen-compose.py ring > lab/compose.yaml
    lab/gen-compose.py chain > lab/chain.yaml

Every link is a docker network of its own with two endpoints, IPv6 only:
- Its host bridge runs no spanning tree, so it passes BPDUs like a cable.
- Docker has only some 30 IPv4 subnets to give out, but plenty of IPv6 ones.
- Docker's firewall passes what is bridged across it, whatever the
  addresses. An "internal" network would drop IPv4 from outside its subnet,
  i.e. all traffic between the switches.
eth0 on the default network is for management and holds the default route;
the plugin leaves it alone.
"""

import argparse
import sys


def ring(n):
    """Nodes (name, priority) and links ((node, port), (node, port))."""
    nodes = [(f"sw{i}", 4096 if i == 1 else None) for i in range(1, n + 1)]
    links = [((f"sw{i}", "lan2"), (f"sw{i % n + 1}", "lan1")) for i in range(1, n + 1)]
    return nodes, links


def chain(n):
    names = ["r1"] + [f"s{i}" for i in range(1, n + 1)] + ["r2"]
    nodes = [(name, {"r1": 0, "r2": 4096}.get(name)) for name in names]
    links = [((a, "lan2"), (b, "lan1")) for a, b in zip(names, names[1:])]
    return nodes, links


def compose(title, nodes, links, args):
    ports = {name: [] for name, _ in nodes}
    for (a, pa), (b, pb) in links:
        ports[a].append((pa, f"{a}-{b}"))
        ports[b].append((pb, f"{a}-{b}"))

    out = [f"# {title}",
           f"# Generated by: lab/gen-compose.py {' '.join(sys.argv[1:])}",
           "# Start with lab/up.sh -f <this file>, drive with LAB_COMPOSE=<this file>",
           "# lab/labctl.py. See lab/README.md.",
           "",
           f"name: {args.name}",
           "",
           "x-switch: &switch",
           "  # Built by lab/up.sh: compose's builder does not see the local dev image.",
           "  image: clixon-switch-lab",
           "  init: true",
           "  cap_add:",
           "    - NET_ADMIN",
           "    # mstpd answers mstpctl with SCM_CREDENTIALS, which needs CAP_SYS_ADMIN.",
           "    - SYS_ADMIN",
           "  healthcheck:",
           '    test: ["CMD", "test", "-f", "/tmp/ready"]',
           "    interval: 1s",
           "    retries: 120",
           "",
           "# IPv6 only: see lab/gen-compose.py.",
           "x-link: &link",
           "  driver: bridge",
           "  enable_ipv4: false",
           "  enable_ipv6: true",
           "",
           "services:"]
    for i, (name, priority) in enumerate(nodes, 1):
        env = {"SWITCH_PORTS": " ".join(p for p, _ in sorted(ports[name])),
               "SWITCH_ADDRESS": f"192.168.{(i - 1) // 250 + 1}.{(i - 1) % 250 + 1}/16"}
        if args.protocol != "none":
            env["STP_PROTOCOL"] = args.protocol
        if priority is not None:
            env["STP_BRIDGE_PRIORITY"] = str(priority)
        if args.max_age:
            env["STP_MAX_AGE"] = str(args.max_age)
        if args.forwarding_delay:
            env["STP_FORWARDING_DELAY"] = str(args.forwarding_delay)
        out += [f"  {name}:",
                "    <<: *switch",
                f"    hostname: {name}",
                "    environment:"]
        out += [f"      {k}: {v}" for k, v in env.items()]
        out += ["    networks:",
                "      default: {gw_priority: 1}"]
        out += [f"      {net}: {{interface_name: {port}}}" for port, net in sorted(ports[name])]
        out.append("")
    out += ["networks:", "  default: {}"]
    out += [f"  {a}-{b}: *link" for (a, _), (b, _) in links]
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("topology", choices=["ring", "chain"])
    ap.add_argument("n", type=int, nargs="?")
    ap.add_argument("--name", help="compose project name")
    ap.add_argument("--protocol", default="RSTP", choices=["RSTP", "STP", "MSTP", "none"])
    ap.add_argument("--max-age", type=int)
    ap.add_argument("--forwarding-delay", type=int)
    args = ap.parse_args()

    if args.topology == "ring":
        n = args.n or 5
        args.name = args.name or "clixon-lab"
        title = f"{n} switches in a ring, sw1 the root."
        text = compose(title, *ring(n), args)
    else:
        n = args.n or 36
        args.name = args.name or "clixon-chain"
        title = (f"A chain of {n + 2} bridges, r1 - s1 - ... - s{n} - r2, r1 priority"
                 " 0, r2 4096: longer than the default max age of 20 allows.")
        text = compose(title, *chain(n), args)
    sys.stdout.write(text)


if __name__ == "__main__":
    main()
